### ISSUE TITLE
Integrate PDF setup into build script

### ISSUE THREAD

**Issue by opoudjis** [metanorma/chocolatey-metanorma#38]
Integrate instructions from https://github.com/metanorma/mn-native-pdf/blob/master/README.adoc, as we are now integrating the functionality of that repository into metanorma

**Comment by opoudjis** [comment]
An essential component of this work is to identify the fonts directory on the current system to be used for PDF generation. The README in mn-native-pdf is mac only.

**Comment by CAMOBAP795** [comment]
@opoudjis @ronaldtse as far as I know globally we are going to replace `puppeteer` with https://github.com/metanorma/mn2pdf

And as far as I understood all needed fonts already available on windows. `mn2pdf` have internal logic for lookup fonts in the specific path on windows

As far as I understood we only need to download `mn2pdf.jar` in scope for chocolatey/homebrew/snap

Only one question from my side how ruby will call this jar, where this jar suppose to be?

**Comment by ronaldtse** [comment]
I believe @opoudjis is planning to embed mn2pdf inside the metanorma-standoc gem.

1. Windows will need the Adobe Source Fonts (https://github.com/fontist/source-fonts), which [fontist](https://github.com/fontist/fontist) should install. These are installed separate from the gem because they are too large.

I noticed that you can use Chocolatey to install fonts, e.g.:
* [Source Code Pro Programming Font](https://chocolatey.org/packages/SourceCodePro)
* [Source Han Code JP](https://chocolatey.org/packages/source-han-code-jp)

Maybe the easiest way to setup is to make a Chocolatey package for Adobe Source Fonts?

**Comment by ronaldtse** [comment]
> An essential component of this work is to identify the fonts directory on the current system to be used for PDF generation. The README in mn-native-pdf is mac only.

The metanorma specific fonts directory is `~/.metanorma/fonts`. The GHA workflows on mn-native-pdf already works for Mac Linux Windows.

**Comment by CAMOBAP795** [comment]
> Maybe the easiest way to setup is to make a Chocolatey package for Adobe Source Fonts?

Probably make sens

As far as I understood both `Source Code Pro Programming Font` and `Source Han Code JP` are fonts from `Adobe Source Fonts` collection, @ronaldtse can you confirm this

If so, will https://github.com/fontist/fontist include all needed `Adobe Source Fonts`?

**Comment by CAMOBAP795** [comment]
Waiting for https://github.com/fontist/fontist/issues/5 to be able to install fonts with `metanorma setup`

**Comment by CAMOBAP** [comment]
Done
