### ISSUE TITLE
Chocolatey package failing automated review

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/chocolatey-metanorma#64]
Looks like Chocolatey has updated their automated validation. @CAMOBAP can you help address this? Thanks!

> 'metanorma' is Submitted.
> Current status = Waiting for Maintainer to take corrective action
> 
> chocolatey-ops left the following comment(s):
> 
> metanorma has failed automated validation.
> 
> Requirements
> 
> Requirements represent the minimum quality of a package that is acceptable. When a package version has failed requirements, the package version requires fixing and/or response by the maintainer. Provided a Requirement has flagged correctly, it must be fixed before the package version can be approved. The exact same version should be uploaded during moderation review.
> 
> The IconUrl element in the nuspec file should be a valid Url. Please correct this More...
> Attention - DO NOT REPLY TO THIS MESSAGE!
> 
> No human moderators see packages until automated checks are passed or the maintainer uses the review comments box to respond. This is very important to understand, if a package has failed any automated checks, you must take action to fix or respond.
> ATTENTION: If your package is failing any automated checks, the ONLY way to get in front of a human moderator is to follow the instructions in the next step.
> If you need to update or respond to package review information, please login and visit your package page (listed below). Use the Add to Review Comments box ONLY, Disqus/Gist comments will not reach a human reviewer.
> This may include review comments prior to the automated checks, check the status on the package - it must be in 'Ready' or 'Responded' to be in front of a human moderator.
> You can also self-reject packages in certain scenarios - see self-reject for more information.
> Package Url: https://community.chocolatey.org/packages/metanorma/1.5.1
> Maintainer(s): ribose, CAMOBAP
> 
> Maintainer Notes
> 
> If we've asked you to make changes, repush your updated package with the exact same version (unless the change we requested was based on an incorrect version).

**Comment by CAMOBAP** [comment]
I got some feedback from moderators:
 - [ ] update licenseUrl
 - [ ] update projectSourceUrl to packed-mn
 - [ ] remove idnits code
 - [ ] add idnits chocolatey package

@ronaldtse I need your opinion/suggestion about `idnits` because we had installation logic of it, but I never checked an actuall content of this package. The idnits contains only unix executable without windows `exe` one. And it worked without it, so questions is do we need idnits on windows at all?

**Comment by ronaldtse** [comment]
@CAMOBAP we can remove idnits. Idnits is no longer invoked by Metanorma directly now. Thanks!

**Comment by CAMOBAP** [comment]
still waiting for Admins to reply...

**Comment by CAMOBAP** [comment]
Admins replied, they force us to do an investigation about virus scanning first and add not about results to package description:

> Am I right in saying that you are part of the team that authors both the underlying software, as well as the Chocolatey package itself?
> If this is the case, then my suggestion would be to create a page on your website, or perhaps create a GitHub issue on your repository (not the packaging repository, but the underlying software repository) that discusses this problem, along with the investigation that has been done to ensure that the detections (which are done outside of Chocolatey) are false positives.
> Once you have done this, you can **_update the description of this package to point to this new documentation page/issue, informing folks as to why there are high detections from VirusTotal_**.

I have never been faced with a such task before so this is an interesting task for me.

But because all issues depend on OCRA and we have plans to move out of OCRA, I would like to confirm this first, @ronaldtse do we need to investigate it at all, or maybe invest time into migration to another packer?

**Comment by ronaldtse** [comment]
The VirusTotal scores are rather arbitrary, incorporating numerous no-name antivirus engines with false positives. As we all know, quantity does not best quality. 

We already have this ticket: https://github.com/metanorma/chocolatey-metanorma/issues/61

Moving out of Orca to Tebako takes time, at least 2 months. There does not seem to be "another packer" for Windows. (ping @maxirmx )

Since VirusTotal is crap, no matter what we do we cannot avoid false positives.

**Comment by ronaldtse** [comment]
@CAMOBAP please update our package description with this link, and ask the Chocolatey package admins to see if they would accept this: https://github.com/metanorma/chocolatey-metanorma/issues/61#issuecomment-968661076 . Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse regarding https://github.com/metanorma/iso-19135/runs/4248559823?check_suite_focus=true

ERROR: Cannot index into a null array. - this happens because changes in idnits-2.16.02.tgz archive structure

Because we already removed it, this issue will be fixed in new release once it will be approved by admins

**Comment by ronaldtse** [comment]
@CAMOBAP do you think Winget gives us more freedom here? Chocolatey seems rather slow in administrative issues.

**Comment by ronaldtse** [comment]
https://github.com/metanorma/winget-metanorma/issues/1

**Comment by CAMOBAP** [comment]
A good question to be honest IDK.

This started happens after the introduction of virus check

https://community.chocolatey.org/packages/metanorma/1.5.2

I think we need to move out of OCRA first, because it behaves really suspiciously, it contains binary in the repository which we cannot control, ruby-packer is more transparent to me because we are building it on our own. Also it seems much faster then OCRA

I will check metanorma/winget-metanorma#1 also

**Comment by CAMOBAP** [comment]
https://ch0.co/moderation - here is  a global review queue

A few more points need to be fixed:
 - [ ] Checksums are required for downloads.
 - [ ] Packages are not allowed modify anything in $env:ChocolateyInstall, with the exception of files inside the package install directory ($env:chocolateyinstall\lib\&lt;package id&gt;) . So please do not download the file to the bin directory. Instead, download to the package directory, and Chocolatey will automatically create a shim. https://docs.chocolatey.org/en-us/features/shim
 - [ ] The iconUrl should be switched from github raw to a CDN: https://docs.chocolatey.org/en-us/create/create-packages#package-icon-guidelines

@ronaldtse are we have >https://raw.githubusercontent.com/metanorma/metanorma.org/main/assets/symbol.svg somewhere on CDN?

**Comment by ronaldtse** [comment]
We can just use https://statically.io/convert/ to get a CDN link for our logo.

**Comment by CAMOBAP** [comment]
Updated package pushed to chocolatey, waiting for review

**Comment by CAMOBAP** [comment]
1.5.2 was approved
